// Generated by CoffeeScript 1.7.1
var bindClickEvents, getArticle, insertThing, splitWords;

$(function() {
  return bindClickEvents();
});

getArticle = function(url, done) {
  return $.ajax({
    method: "GET",
    url: url
  }).done(function(result) {
    var left, paragraph, right;
    h = $(result);

    //  left = result.indexOf("<p>");
    //  right = result.indexOf("</p>");
    //  paragraph = result.slice(left, right + 4);
    paragraph = h.find("#mw-content-text > p").first().html();
    return done(paragraph);
  });
};

bindClickEvents = function() {
  var id;
  id = 0;
  $("a").each(function() {
    $(this).attr("data-unique-nobody-use-this-link-id", id);
    if ($(this).attr("data-unique-nobody-use-this-link-opened") !== "true") {
      $(this).attr("data-unique-nobody-use-this-link-opened", "false");
    }
    return id += 1;
  });
  $("a").unbind("click");
  return $("a").click(function(evt) {
    var element, linkHtml, location, pHtml, parent;
    element = $(evt.target);
    id = $(this).attr("data-unique-nobody-use-this-link-id");
    if (element.attr("data-unique-nobody-use-this-link-opened") === "true") {
      element.attr("data-unique-nobody-use-this-link-opened", "false");
      $(".expand-div[data-id='" + id + "']").remove();
      console.log("removed");
    } else {
      element.attr("data-unique-nobody-use-this-link-opened", "true");
      parent = element.parent();
      linkHtml = element[0].outerHTML;
      pHtml = parent.html();
      location = pHtml.indexOf(linkHtml) + linkHtml.length;
      console.log(pHtml.slice(0, location));
      insertThing(parent, location, id, element.attr("href"));
    }
    return false;
  });
};

insertThing = function(para, offset, id, url) {
  return para.each(function() {
    var current, height, i, inserted, lastHtml, text, words;
    current = $(this);
    text = current.html();
    words = splitWords(text.slice(offset));
    current.html(para.html().slice(0, offset));
    height = current.height();
    i = 1;
    inserted = false;
    while (i < words.length) {
      lastHtml = current.html();
      current.html(lastHtml + " " + words[i]);
      if (current.height() > height) {
        current.html(lastHtml);
        inserted = true;
        current.html(lastHtml + (" <div class=\"expand-div\" data-id=\"" + id + "\"></div> "));
        current.html(current.html() + " " + words.slice(i).join(" "));
        bindClickEvents();
        getArticle(url, (function(_this) {
          return function(result) {
            $(".expand-div[data-id='" + id + "']").html(result);
            return bindClickEvents();
          };
        })(this));
        return;
      }
      i++;
    }
    console.log(current);
    bindClickEvents();
  });
};

splitWords = function(text) {
  var currentWord, endOfTag, i, words;
  words = [];
  currentWord = "";
  i = 0;
  while (i < text.length) {
    if (text[i] === " ") {
      words.push(currentWord + " ");
      currentWord = "";
    } else if (text.slice(i, i + 3) === "<a ") {
      words.push(currentWord);
      currentWord = "";
      endOfTag = text.slice(i).indexOf("</a>") + 4;
      words.push(text.slice(i, i + endOfTag));
      i += endOfTag;
    } else {
      currentWord += text[i];
    }
    i += 1;
  }
  words.push(currentWord);
  return words;
};
